spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/inject?charset=utf-8
    driver-class-name: org.postgresql.Driver
    hikari:
      username: postgres
      password: postgres
      minimum-idle: 1
      maximum-pool-size: 2

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    icu.cucurbit.inject.dao: debug
